// automatically generated by the FlatBuffers compiler, do not modify

package IndisMQ

const (
	ActionGET = 0
	ActionRESPONSE = 1
	ActionSET = 2
	ActionNEW = 3
	ActionAPPEND = 4
	ActionREPLACE = 5
	ActionUPDATE = 6
	ActionDELETE = 7
	ActionPUBLISH = 8
	ActionSUBSCRIBE = 9
	ActionUNSUBSCRIBE = 10
	ActionCONNECT = 11
	ActionJOIN = 12
)

var EnumNamesAction = map[int]string{
	ActionGET:"GET",
	ActionRESPONSE:"RESPONSE",
	ActionSET:"SET",
	ActionNEW:"NEW",
	ActionAPPEND:"APPEND",
	ActionREPLACE:"REPLACE",
	ActionUPDATE:"UPDATE",
	ActionDELETE:"DELETE",
	ActionPUBLISH:"PUBLISH",
	ActionSUBSCRIBE:"SUBSCRIBE",
	ActionUNSUBSCRIBE:"UNSUBSCRIBE",
	ActionCONNECT:"CONNECT",
	ActionJOIN:"JOIN",
}

