// automatically generated by the FlatBuffers compiler, do not modify

package IndisMQ

const (
	ActionGET = 0
	ActionSET = 1
	ActionNEW = 2
	ActionAPPEND = 3
	ActionREPLACE = 4
	ActionUPDATE = 5
	ActionDELETE = 6
	ActionSUBSCRIBE = 7
	ActionUNSUBSCRIBE = 8
	ActionCONNECT = 9
	ActionJOIN = 10
)

var EnumNamesAction = map[int]string{
	ActionGET:"GET",
	ActionSET:"SET",
	ActionNEW:"NEW",
	ActionAPPEND:"APPEND",
	ActionREPLACE:"REPLACE",
	ActionUPDATE:"UPDATE",
	ActionDELETE:"DELETE",
	ActionSUBSCRIBE:"SUBSCRIBE",
	ActionUNSUBSCRIBE:"UNSUBSCRIBE",
	ActionCONNECT:"CONNECT",
	ActionJOIN:"JOIN",
}

