// automatically generated by the FlatBuffers compiler, do not modify

package IndisMQ

const (
	ActionGET = 0
	ActionSET = 1
	ActionNEW = 2
	ActionAPPEND = 3
	ActionREPLACE = 4
	ActionUPDATE = 5
	ActionDELETE = 6
	ActionPUBLISH = 7
	ActionSUBSCRIBE = 8
	ActionUNSUBSCRIBE = 9
	ActionCONNECT = 10
	ActionJOIN = 11
)

var EnumNamesAction = map[int]string{
	ActionGET:"GET",
	ActionSET:"SET",
	ActionNEW:"NEW",
	ActionAPPEND:"APPEND",
	ActionREPLACE:"REPLACE",
	ActionUPDATE:"UPDATE",
	ActionDELETE:"DELETE",
	ActionPUBLISH:"PUBLISH",
	ActionSUBSCRIBE:"SUBSCRIBE",
	ActionUNSUBSCRIBE:"UNSUBSCRIBE",
	ActionCONNECT:"CONNECT",
	ActionJOIN:"JOIN",
}

