// automatically generated by the FlatBuffers compiler, do not modify

package IndisMQ

const (
	AuthErrNONE = 0
	AuthErrINVALID = 1
	AuthErrUNAUTHORIZED = 2
)

var EnumNamesAuthErr = map[int]string{
	AuthErrNONE:"NONE",
	AuthErrINVALID:"INVALID",
	AuthErrUNAUTHORIZED:"UNAUTHORIZED",
}

