// automatically generated by the FlatBuffers compiler, do not modify

package IndisMQ

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Meta struct {
	_tab flatbuffers.Table
}

func GetRootAsMeta(buf []byte, offset flatbuffers.UOffsetT) *Meta {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Meta{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Meta) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Meta) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Meta) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MetaAddKey(builder *flatbuffers.Builder, Key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(Key), 0)
}
func MetaAddValue(builder *flatbuffers.Builder, Value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Value), 0)
}
func MetaEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
