// automatically generated by the FlatBuffers compiler, do not modify

package IndisMQ

const (
	MsgTypeREQ = 0
	MsgTypeREP = 1
	MsgTypeCAST = 2
)

var EnumNamesMsgType = map[int]string{
	MsgTypeREQ:"REQ",
	MsgTypeREP:"REP",
	MsgTypeCAST:"CAST",
}

